### ISSUE TITLE
Return assertion errors

### ISSUE THREAD

**Issue by Dkendal** [batate/shouldi#10]
First of all thanks for this module, it makes testing much more succinct. Is there any way to have matchers actually return their errors though? 
Here I have  block of matchers inside of a with block,
``` elixir
  with "an atom" do
    setup context do
      assign context,
        spring: cast(Semester, :spring),
        summer: cast(Semester, :summer),
        winter: cast(Semester, :winter)
    end

    should_assign_key spring: {:ok, "01"}
    should_assign_key summer: {:ok, "05"}
    should_assign_key winter: {:ok, "09"}
  end
```
 in the event of any failing I get the not so useful error message:
> 1) test with 'an atom': should have passing matchers (SemesterTest)
     test/lib/semester_test.exs:42
     ** (ShouldI.MultiError) multiple matcher errors

Obviously it would be ideal if I were to just get the individual assertion errors. This is with version 0.2.1 and elixir version 1.0.2.

**Comment by ericmj** [comment]
You need to configure ExUnit to use ShouldI's formatter. Add this to your test_helper.exs file: `ExUnit.start(formatters: [ShouldI.CLIFormatter])`. I will update the readme with this information.

**Comment by Dkendal** [comment]
Thanks Eric, that solved that. Are with blocks not intended to be nested? I got unexpected behavior when they're nested and used with the built in matchers (keys not defined on context)?

**Comment by ericmj** [comment]
We are using nested with blocks so they work for us at least :). Can you show the full error you get and a snippet of your code?

**Comment by Dkendal** [comment]
Sure thing. In this example the matcher works as expected in the first with block, and the context works properly in the second with block with a standard test - but the problem arises when you try to use a should_* matcher in a nested with block.
https://gist.github.com/Dkendal/d12e933e07d4e47f699a

**Comment by ericmj** [comment]
I have pushed a possible fix to master. Can you please try it out?
