### ISSUE TITLE
In the current release v0.2.2 you need to add `use ExUnit.Case` 

### ISSUE THREAD

**Issue by tonini** [batate/shouldi#17]
In the current `v0.2.2` you need add `use ExUnit.Case` before `use ShouldI`.

This could be a bit confusing to people who reading the instruction on the `README`.

As I can see @lpil fixed this with https://github.com/batate/shouldi/commit/baa39867fb2a60a632d66af1dba1b8b5134c7adb, so could we have soon a `v0.2.3` release with that? 

That would be great!  :+1: 

Cheers

Samuel

**Comment by lpil** [comment]
:+1:

**Comment by alxndr** [comment]
:+1:

**Comment by ericmj** [comment]
Released.

**Comment by tonini** [comment]
Thanks :heart:
