### ISSUE TITLE
PR #18 broke aliases/imports being visible in `setup/1` blocks

### ISSUE THREAD

**Issue by limhoff-r7** [batate/shouldi#20]
I was testing that PR #18 improved my test load time.  I had been using the released 0.2.3 and changed to using master HEAD

```diff
diff --git a/mix.exs b/mix.exs
index 001da59..817d1b1 100644
--- a/mix.exs
+++ b/mix.exs
@@ -72,7 +72,8 @@ defmodule Metasploit.Pro.Mixfile do
      {:phoenix_live_reload, "~> 0.4"},
      {:postgrex, ">= 0.0.0"},
      {:plug_rails_cookie_session_store, "~> 0.1.0"},
-     {:shouldi, "~> 0.2.3", only: :test}
+     # Need PR #18 to fix test load time, not released in 0.2.3
+     {:shouldi, github: "batate/shouldi", ref: "024fb333ddfbcdd8efbfb909c12ead058e56b6c2", only: :test}
     ]
   end
 end
```

The test load time is faster, but aliases and imports from `use`s or the outer module stopped having an  effect inside `setup/1` blocks.  I'm getting new errors like ` undefined function: User.friendly_token/0 (module User is not available)`  when the test code is unchanged and the alias exists:

```elixir
defmodule Metasploit.Pro.Api.V1.UserControllerTest do
  use Metasploit.Pro.ConnCase

  alias Metasploit.Pro.User
  # ...
end
```

# Work-arounds:
1. Qualify all calls (so ignore imports)
2. Use original names (so ignore aliases)

**Comment by ericmj** [comment]
@josevalim Do you know why this might be happening?

**Comment by josevalim** [comment]
Ah, it is because the def call is happening inside the anonymous function that is defined at the top. I think we should revert fix for setup and leave it as before. We could at least reduce the variable usage though.

**Comment by ericmj** [comment]
@josevalim Please ping me when free so we can discuss the fix.

**Comment by ericmj** [comment]
@limhoff-r7 Please try the latest commit on master and let us know if it works.

**Comment by limhoff-r7** [comment]
I can confirm 4c1b9c9 allows aliases to be accessible in setup blocks.
