### ISSUE TITLE
Allow users to mark tests as pending and document method.

### ISSUE THREAD

**Issue by lpil** [batate/shouldi#21]
Said tests should not run, but should be reported in the output as pending.

**Comment by ericmj** [comment]
I would say this out of scope for shouldi. Shouldi builds on top of exunit and you can achieve similar functionality with exunit tags.

**Comment by lpil** [comment]
After looking at some other projects I was under the impression that with `ExUnit` tests would be skipped if annotated with `@tag :pending`, but this doesn't seem to be the case for the `should` macro. Perhaps I'm doing something wrong here- I don't quite get tags yet.

**Comment by ericmj** [comment]
The `should` macro expands to the `test` macro so tags work for both.
