### ISSUE TITLE
new version on hex.pm for elixir 1.2 compatibility?

### ISSUE THREAD

**Issue by adamkittelson** [batate/shouldi#26]
Looks like @ericmj added a commit a while back that changes `with` to `having` since `with` conflicts with the new special form added in Elixir 1.2.

I've confirmed that my tests pass using shouldi master (`54559b9a694db4d7cf4c62b365a36686844eb3ea`) after updating `with` to `having` in my tests. Just thought I'd nudge to see if there are any blockers on releasing an updated shouldi on hex.pm.

Thanks!

**Comment by batate** [comment]
Eric is on this. Sorry for the delay.

-bt

On Thu, Dec 17, 2015 at 3:02 PM, Adam Kittelson <notifications@github.com>
wrote:

> Looks like @ericmj <https://github.com/ericmj> added a commit a while
> back that changes with to having since with conflicts with the new
> special form added in Elixir 1.2.
>
> I've confirmed that my tests pass using shouldi master (
> 54559b9a694db4d7cf4c62b365a36686844eb3ea) after updating with to having
> in my tests. Just thought I'd nudge to see if there are any blockers on
> releasing an updated shouldi on hex.pm.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/batate/shouldi/issues/26>.
>



-- 

*Bruce Tate*  |  *CTO*  |  *512.772.4312*

*i**can**make**it**better**.com* <http://icanmakeitbetter.com>

*Innovation + Research. Made Simple*

**Comment by steffenix** [comment]
elixir 1.2 is out, any update?

**Comment by lpil** [comment]
:+1:

**Comment by ericmj** [comment]
Released v0.3.0
