### ISSUE TITLE
Not very detailed error info when a matcher fails

### ISSUE THREAD

**Issue by olcai** [batate/shouldi#31]
I'm trying out ShouldI for a new Elixir project I'm working on, and I really like it! However, I'm not very happy with the error I get when a matcher fails. For example, adding a failing matcher in `test/context_matcher_test.exs` gives me this output:

```
  1) test having 'another level': should have passing matchers (ContextMatcherTest)
     test/context_matcher_test.exs:2
     ** (ShouldI.MultiError) multiple matcher errors
     stacktrace:
       test/context_matcher_test.exs:2
```
Is it a feature or a bug that I get no line number information in the stacktrace? Is there any another way of finding out the specific matcher that failed?

**Comment by batate** [comment]
Eric, what do you think? Is there an easy way to extract a line number? Can
you point Erik to the right direction for a potential pull request?

-bt



On Thu, May 26, 2016 at 2:55 AM, Erik Timan <notifications@github.com>
wrote:

> I'm trying out ShouldI for a new Elixir project I'm working on, and I
> really like it! However, I'm not very happy with the error I get when a
> matcher fails. For example, adding a failing matcher in
> test/context_matcher_test.exs gives me this output:
>
>   1) test having 'another level': should have passing matchers (ContextMatcherTest)
>      test/context_matcher_test.exs:2
>      ** (ShouldI.MultiError) multiple matcher errors
>      stacktrace:
>        test/context_matcher_test.exs:2
>
> Is it a feature or a bug that I get no line number information in the
> stacktrace? Is there any another way of finding out the specific matcher
> that failed?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/batate/shouldi/issues/31>
>



-- 

*Bruce Tate*  |  *CTO*  |  *512.772.4312*

We are now part of ISA and SoapBoxSample – together leading the way in
online communities, sampling and research. *Learn more.
<http://www.soapboxsample.com/soapbox-expands-with-recent-acquisition/>*

*i**can**make**it**better**.com* <http://icanmakeitbetter.com>

*Innovation + Research. Made Simple*

**Comment by ericmj** [comment]
Fixed in the latest release.
