### ISSUE TITLE
Use of having conflicts with Ecto.Query

### ISSUE THREAD

**Issue by mcelaney** [batate/shouldi#32]
Tried to import Ecto.Query to run an ad-hoc query during a test. ShouldI conflicts on the having macro.

It's an edge case I guess - but I thought I'd bring it up.

```
defmodule SR.System.TenantTest do
  @moduledoc false

  use ShouldI, async: true

  import Ecto.Query

  having "a valid tenant with an average > 50% paid on time" do
    #blah blah blah
  end
end

# function having/2 imported from both Ecto.Query and ShouldI, call is ambiguous
```

**Comment by ericmj** [comment]
For now I think you will have exclude `having` when importing: `import Ecto.Query, except: [having: 2]`.

We already changed `with` to `having` due to conflicts with Elixir.
